language: java
jdk:
  - oraclejdk8
  - openjdk8
sudo: false
dist: trusty

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test --info

# cache gradle dependencies
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
